name: CI/CD

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday
  workflow_dispatch:

jobs:
  # ---------------------------------------------------------------------------- #
  #                                VALIDATE SCHEMA                               #
  # ---------------------------------------------------------------------------- #

  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Test token list schema
        run: just test-schema

  # ---------------------------------------------------------------------------- #
  #                               CHECK DUPLICATES                               #
  # ---------------------------------------------------------------------------- #

  check-duplicates:
    name: Check for Duplicates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Check for duplicate entries
        run: just test-duplicates

  # ---------------------------------------------------------------------------- #
  #                               VERIFY CHECKSUMS                               #
  # ---------------------------------------------------------------------------- #

  verify-checksums:
    name: Verify Address Checksums
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Verify address checksums
        run: just test-checksums

  # ---------------------------------------------------------------------------- #
  #                               VALIDATE METADATA                              #
  # ---------------------------------------------------------------------------- #

  validate-metadata:
    name: Validate Token Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Test token metadata
        run: just test-metadata

  # ---------------------------------------------------------------------------- #
  #                                     BUILD                                    #
  # ---------------------------------------------------------------------------- #

  build:
    name: Build Token List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Build token list
        run: just build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tokenlist
          path: token-list/build.json
          retention-days: 7

  # ---------------------------------------------------------------------------- #
  #                                   RUN TESTS                                  #
  # ---------------------------------------------------------------------------- #

  run-tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Run tests
        run: just test

  # ---------------------------------------------------------------------------- #
  #                               VALIDATE DECIMALS                              #
  # ---------------------------------------------------------------------------- #

  check-decimals:
    name: Validate Token Decimals via RPC
    runs-on: ubuntu-latest
    needs: [validate-schema, check-duplicates, verify-checksums, validate-metadata, build, run-tests]
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Test decimals
        env:
          ROUTEMESH_API_KEY: ${{ secrets.ROUTEMESH_API_KEY }}
        run: just test-decimals

  # ---------------------------------------------------------------------------- #
  #                              VALIDATION SUMMARY                              #
  # ---------------------------------------------------------------------------- #

  summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [validate-schema, check-duplicates, verify-checksums, validate-metadata, build, run-tests, check-decimals]
    if: always()
    steps:
      - name: Check job results
        run: | #shell
          echo "## Validation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Schema Validation | ${{ needs.validate-schema.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Duplicate Check | ${{ needs.check-duplicates.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Checksum Verification | ${{ needs.verify-checksums.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Metadata Validation | ${{ needs.validate-metadata.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Test Suite | ${{ needs.run-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Decimals Check | ${{ needs.check-decimals.result }} |" >> $GITHUB_STEP_SUMMARY

      - name: Fail if any job failed
        if: | #shell
          needs.validate-schema.result == 'failure' ||
          needs.check-duplicates.result == 'failure' ||
          needs.verify-checksums.result == 'failure' ||
          needs.validate-metadata.result == 'failure' ||
          needs.build.result == 'failure' ||
          needs.run-tests.result == 'failure' ||
          needs.check-decimals.result == 'failure'
        run: exit 1

  # ---------------------------------------------------------------------------- #
  #                                    DEPLOY                                    #
  # ---------------------------------------------------------------------------- #

  deploy:
    name: Build and Deploy Token List
    runs-on: ubuntu-latest
    needs: [validate-schema, check-duplicates, verify-checksums, validate-metadata, build, run-tests, check-decimals]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # run only on push to `main`
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Build token list
        run: just build

      - name: Configure Git
        run: | #shell
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push token list
        run: | #shell
          git add token-list/build.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "build: update build.json [skip ci]"
            git push
          fi

      - name: Add deployment summary
        run: | #shell
          echo "## Deploy result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Details" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: https://files.sablier.com/token-list/build.json" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Total Tokens**: $(jq '.tokens | length' token-list/build.json)" >> $GITHUB_STEP_SUMMARY
          echo "- **Chains**: $(jq '[.tokens[].chainId] | unique | length' token-list/build.json)" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: $(jq -r '"\(.version.major).\(.version.minor).\(.version.patch)"' token-list/build.json)" >> $GITHUB_STEP_SUMMARY
