name: "CI: Decimals"

on:
  workflow_call:
    secrets:
      ROUTEMESH_API_KEY:
        required: true

jobs:
  check-decimals:
    name: Validate Token Decimals via RPC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Test decimals
        env:
          ROUTEMESH_API_KEY: ${{ secrets.ROUTEMESH_API_KEY }}
        run: just test-decimals
