name: Token List CI

on:
  pull_request:
    branches:
      - main

jobs:
  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Validate token list schema
        run: bun run validate:schema

  check-duplicates:
    name: Check for Duplicates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Check for duplicate entries
        run: bun run validate:duplicates

  verify-checksums:
    name: Verify Logo Checksums
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Verify logo checksums
        run: bun run validate:checksums

  validate-metadata:
    name: Validate Token Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Validate token metadata
        run: bun run validate:metadata

  build-test:
    name: Build Token List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Build token list
        run: bun run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tokenlist
          path: lists/build/tokenlist.json
          retention-days: 7

  run-tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Run tests
        run: bun test

  summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [validate-schema, check-duplicates, verify-checksums, validate-metadata, build-test, run-tests]
    if: always()
    steps:
      - name: Check job results
        run: | #shell
          echo "## Validation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Schema Validation | ${{ needs.validate-schema.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Duplicate Check | ${{ needs.check-duplicates.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Checksum Verification | ${{ needs.verify-checksums.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Metadata Validation | ${{ needs.validate-metadata.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build Test | ${{ needs.build-test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Test Suite | ${{ needs.run-tests.result }} |" >> $GITHUB_STEP_SUMMARY

      - name: Fail if any job failed
        if: | #shell
          needs.validate-schema.result == 'failure' ||
          needs.check-duplicates.result == 'failure' ||
          needs.verify-checksums.result == 'failure' ||
          needs.validate-metadata.result == 'failure' ||
          needs.build-test.result == 'failure' ||
          needs.run-tests.result == 'failure'
        run: exit 1
